### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by ghost** [Sheeprider/BitBucket-api#5]
This library is nice. Is there documentation somewhere?

List all of an authenticated user's repositories https://gist.github.com/matthew-campbell/5471630

**Comment by markeganfuller** [comment]
The library definitely needs some docs. 

@matthew-campbell  Thanks for that Gist its exactly what I was looking for.

**Comment by Sheeprider** [comment]
Here it is : https://bitbucket-api.readthedocs.org/en/latest/
I couldn't get private's tests documentation to work, so it's still missing.
The rest should be fine, even if it's still incomplete / imprecise.

**Comment by markeganfuller** [comment]
Great, thanks.

**Comment by ghost** [comment]
@Sheeprider I like the docs :)
